version: '3.8'

services:
  app:
    build:
      context: .
      target: ${TARGET:-dev}
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}