version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      target: ${TARGET:-dev}
    container_name: frontend-container
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3030:3030"
    depends_on:
      - postgres
    command: sh -c "npx prisma generate && npx prisma migrate dev && npm run dev"
    environment:
      - NODE_ENV=development

  postgres:
    image: postgres:latest
    container_name: postgres_dbs
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
