version: '3.8'

services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: node_app
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3030:3030"
    depends_on:
      - postgres
    command: sh -c "npx prisma generate && npm run dev"
    environment:
      - NODE_ENV=development

  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  postgres_data:
